auteur = "Amélie Levasseur-Raymond"
titre = "Papiers numériques"
soustitre = "Recueil de textes"
description = "Description"
copyright = "Les contenus de ce recueil sont sous [licence CC BY-NC-SA](http://creativecommons.org/licenses/by-nc-sa/4.0/) : Attribution - Pas d’utilisation commerciale - Partage dans les mêmes conditions"
edition = "Fabrique"
mention = "Fabrique de Amélie Levasseur-Raymond"
isbn = ""
licence = "CC BY-NC-SA"
couverture = "/images/Logo_ALR_pos_Blanc.png"
logo = "/images/Logo_ALR_pos_Blanc.png"
search = false
format = "portrait"
indentation = "oui"
marques = "crop"
quatrieme = "oui"
readingtime = "oui"
bloctexte = "justify"  # s'applique au print seulement

