auteur = "Amélie Levasseur-Raymond"
titre = "Mes textes"
soustitre = "Sous-titre"
description = "Description"
copyright = "CC BY-NC-SA"
edition = "Fabrique"
mention = "Fabrique"
isbn = ""
licence = "CC BY-NC-SA"
couverture = "images/Logo_ALR_pos_Noir.png"
logo = "images/Logo_ALR_pos_Noir.png"
search = false
format = "portrait"
indentation = "oui"
marques = "crop"
quatrieme = "oui"
readingtime = "oui"
bloctexte = "justify"  # s'applique au print seulement

